# deploy to github pages for my userid
# don't really need a build so decided to go for linting??? 

# checked with https://config.travis-ci.com/explore

# to campbe13.github.io

# linter not working properly so test without the script
language: node_js
node_js:
  - 13
os: linux
dist: bionic
deploy:
  provider: pages
  token: $TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
#script: ./lint.sh

